### ISSUE TITLE
Revisar registro

### ISSUE THREAD

**Issue by AlefMemTav** [fga-eps-mds/2022-1-EuPescador-Doc#45]
### Descrição:
Eu, como Pesquisador, desejo revisar um registro do sistema para ter controle sobre eles, aprovando-os ou não.

### Tarefas
Seção para tarefas (tasks) para issues mais complexas ou sub-tarefas. 
- [ ] Usar componente Form
- [ ] Aprovar registro via clique no botão de aprovar
- [ ] Cancelar alteração do registro via clique no botão de cancelar
- [ ] Editar registro (CRUD)
- [ ] Teste de revisão

### Critérios de aceitação
- [ ]
- [ ]

### Comentários ou Observações
O botão de aprovar nesta história é o mesmo botão que confirma a edição de registros em Editar registro(CRUD).
O botão de cancelar anula a revisão de registro, mantendo-o inalterado.
A ação do botão deletar pertence à história de usuário Deletar registro(CRUD).
